// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteHat.Data.WhiteHatDbContext;

#nullable disable

namespace WhiteHat.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240726102618_AddedConstruction and seed")]
    partial class AddedConstructionandseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteHat.Models.Construction", b =>
                {
                    b.Property<int>("ConstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConstructionId"));

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasAnnotation("DefaultValue", "false");

                    b.Property<string>("ReadMore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("ConstructionId");

                    b.ToTable("Constructions");

                    b.HasData(
                        new
                        {
                            ConstructionId = 1,
                            Description = "I am Upvc Description check",
                            Image = "",
                            IsDeleted = false,
                            ReadMore = "I am Upvc Readmore Check",
                            Title = "Upvc"
                        },
                        new
                        {
                            ConstructionId = 2,
                            Description = "I am Upvc Description check 2",
                            Image = "",
                            IsDeleted = false,
                            ReadMore = "I am Upvc Readmore Check 2",
                            Title = "Upvc2"
                        });
                });

            modelBuilder.Entity("WhiteHat.Models.UserInfo", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasAnnotation("DefaultValue", "false");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("UserId");

                    b.ToTable("UserInfoes");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("9668dc45-23af-4cae-a85b-3711bb1b4247"),
                            FirstName = "Test",
                            GenderId = 1,
                            IsDeleted = false,
                            LastName = "User",
                            Mobile = "+9808311151"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
